apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warden-auth
  namespace: warden
  annotations:
    nginx.ingress.kubernetes.io/load-balance: "ewma"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-connections: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: auth.warden.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: warden-auth
                port:
                  number: 8082
